[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.install]
cmds = ["mvn clean package -DskipTests"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "java -jar target/circular-fashion-1.0.0.jar"
